api:
  base_url: "http://api.openweathermap.org/data/2.5/air_pollution/history"
  # Date range for historical data (YYYY-MM-DD format)
  start_date: "2024-12-01"
  end_date: "2024-12-03"       

etl:
  save_raw: true        
  raw_path: "data/raw"  
  processed_path: "data/processed"  

app:
  title: "Clima en nuestras ciudades"